defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections_dir: _collections
collections:
  akce:
    output: true
    permalink: /:collection/:path:output_ext
  aviblog:
    output: true
    permalink: /:collection/:path:output_ext
